name: Python flask-application
env:
  DEPLOY_PACKAGE_NAME : "version-${{ github.sha }}"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test-Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Create a .zip package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    - name: Creating Artifacts and putting to dewnloads folder
      run: |
          mkdir downloads
          mv *.zip downloads
          
    - name: Use the upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with:
          name: assets-for-download
          path: downloads
          
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: downloads  
      
      
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: The build is created successfully - ${{ env.DEPLOY_PACKAGE_NAME }}
        photo: tests/github.png


  Delivery:
  
        runs-on: self-hosted
        needs: [Test-Build]
        
        steps:
        - uses: actions/checkout@v2
        - name: Run Ansible Playbook
          run: |
               cd /home/vova/ans_project
               ansible -m ping all -vv
             
        - name: Download the artifact
          uses: actions/download-artifact@v2
          with:
              name: assets-for-download
              path: downloads

